version: "3"
services:
  mysql:
    image: mysql:5.6
    volumes:
      - mysqldb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  mariadb:
    image: mariadb:10.3.29
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      DB_VENDOR: mysql
      DB_DATABASE: test
      DB_USER: root
      DB_ADDR: mysql
      DB_PASSWORD: root
      JDBC_PARAMS: useSSL=false&allowPublicKeyRetrieval=true
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

  oidc-bridge:
    build: .
    ports:
      - 3333:3333
    volumes:
      - ./jwks.json:/opt/jwks.json
    environment:
      SERVER_URL: http://localhost
      SERVER_PORT: 3333
      DATABASE_URL: mariadb://test:test@mariadb:3306/test
      JWKS_KEY_FILE_PATH: /opt/jwks.json
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      CLIENT_REDIRECT_URL: ${CLIENT_REDIRECT_URL}
      CLIENT_POST_LOGOUT_REDIRECT_URL: ${CLIENT_POST_LOGOUT_REDIRECT_URL}
      USE_PROXY: "true"
      COOKIE_SECRET: ${COOKIE_SECRET}
      COOKIE_MAX_AGE: "300000"
      REDIS_URL: redis
      REDIS_PORT: 6379
      PASSWORD_HASH_SETTINGS: ${PASSWORD_HASH_SETTINGS}

  oidc-bridge-impersonate:
    build: .
    ports:
      - 4444:4444
    volumes:
      - ./jwks.json:/opt/jwks.json
    hostname: impersonate
    environment:
      SERVER_URL: http://impersonate
      SERVER_PORT: 4444
      DATABASE_URL: mariadb://test:test@mariadb:3306/test
      JWKS_KEY_FILE_PATH: /opt/jwks.json
      CLIENT_ID: ${IMPERSONATE_CLIENT_ID}
      CLIENT_SECRET: ${IMPERSONATE_CLIENT_SECRET}
      CLIENT_REDIRECT_URL: ${IMPERSONATE_CLIENT_REDIRECT_URL}
      CLIENT_POST_LOGOUT_REDIRECT_URL: ${IMPERSONATE_CLIENT_POST_LOGOUT_REDIRECT_URL}
      USE_PROXY: "true"
      COOKIE_SECRET: ${COOKIE_SECRET}
      COOKIE_MAX_AGE: "300000"
      REDIS_URL: redis
      REDIS_PORT: 6379
      PASSWORD_HASH_SETTINGS: ${PASSWORD_HASH_SETTINGS}
      IMPERSONATE_MASTER_PASSWORD: ${IMPERSONATE_MASTER_PASSWORD}
  
volumes:
  mariadb_data: {}
  mysqldb_data: {}