version: "3"
services:
  mysql:
    image: mysql:5.6
    volumes:
      - mysqldb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  mariadb:
    image: mariadb:10.3.29
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      DB_VENDOR: mysql
      DB_DATABASE: test
      DB_USER: root
      DB_ADDR: mysql
      DB_PASSWORD: root
      JDBC_PARAMS: useSSL=false&allowPublicKeyRetrieval=true
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

volumes:
  mariadb_data: {}
  mysqldb_data: {}